### ISSUE TITLE
Client: Problem bei mehreren zusätzlichen Informationen auf einer Seite

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#12]
Es scheint immer noch das Problem zu bestehen,d ass es nur eine nicht angeklickte zusätzliche Information geben kann (sonst kommt man nicht weiter)
![grafik](https://user-images.githubusercontent.com/50660709/68308290-e97ed600-00ac-11ea-867f-911ba0cc6662.png)

**Comment by peterfromberger** [comment]
Ja, das stimmt. das ist ein Bug, den ich aus der vorherigen Version mit übernommen habe. Wie immer, ich arbeite daran... :-)

**Comment by peterfromberger** [comment]
Kannts du mir noch schreiben welche Sitzung Modul und Lektion das Beispiel kommt?

**Comment by SonjaSchroeder** [comment]
bspw. http://134.76.18.241/client/overview/1/2/7

**Comment by peterfromberger** [comment]
Ich denke, jetzt funktioniert alles so, wie es sollte. Bitte beachtet: man kann MAXIMAL DREI optionale Infos oder optionale Tasks in Reihe schalten! Bei vier geht es nicht mehr...ich kann das auch noch erweitern auf mehr als drei, aber nur, wenn es unbedingt notwendig ist.
