### ISSUE TITLE
Client: bei Links in Info-Text wird Link nicht in neuem Tab geöffnet, sondern im Interventions-tab und man wird ausgeloggt

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#13]

**Comment by peterfromberger** [comment]
Bitte immer ein beispiel und die URL bzw. Modul-Sitzung-Lektion zum Beispiel angeben! danke

**Comment by SonjaSchroeder** [comment]
bspw. http://134.76.18.241/client/overview/5/2/7

Als ich es eben probiert ahbe, hat es funktioniert

**Comment by louisabauer** [comment]
Ich hab es eben in der gleichen Lektion wie Sonja an meinem Laptop probiert und bei mir funktioniert es nicht. Sonja und ich nutzen beide firefox als Browser, also wahrscheinlich gibt es da eine Einstellung im Browser ob Links in einem neuen Tab geöffnet werden oder im gleichen... Gibt es eine Möglichkeit in mytabu zu "erzwingen", dass Links in einem neuen Tab geöffnet werden?

**Comment by louisabauer** [comment]
Es ist bei mir inzwischen aber auch so, dass man nach öffnen des Links über die zurück Funktion im Browser wieder zu mytabu kommt ohne ausgeloggt zu werden, also ist das nicht so tragisch

**Comment by peterfromberger** [comment]
Sollte beom  nächsten update so sein, dass alle externen links in einem neuenTab geöffnet werden...
