### ISSUE TITLE
Client: Bei Quiz wird bei richtiger Antowrt "das ist falsch" angezeigt

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#15]
Ich weiß nicht, ob das daran liegt, weil das noch die Platzhalter-Quizze sind... aber beide antworten werden als falsch angezeigt, man kommt trotzdem nach Auswählen der zweiten Option weiter.
![grafik](https://user-images.githubusercontent.com/50659143/68382938-fc4ce580-0154-11ea-8a02-7bbd3f625c93.png)

**Comment by peterfromberger** [comment]
Das ist kein Bug! Das ist das neue Feedback: du musst im Backend das Feedback eingeben, dass hier angezeigt werden soll (bei Erstellung wird das Feedback automatisch mit "Das ist falsch." gefüllt. Man sollte das natürlich entsprechend seiner Aufgabe ändern. Hier beispielsweise: "B ist richtig. B ist ein wunderbarer Buchstabe, den man immer auswählen kann."

Die Idee (und das war ja ein Wunsch von euch!) ist, dass man hier nun ein konkretes Feedback individuell zur Aufgabe passend eingeben kann. Das gilt für alle Multiple-Choice-Tasks und auch für die Quizzes!

**Comment by louisabauer** [comment]
Ah okay, ich wusste schon, dass es jetzt eine Feedback-Funktion gibt, mir war nur nicht klar, dass du als default für das Feedback überall "das ist falsch" einsetzt und war jetzt beim durchklicken etwas erstaunt...

**Comment by peterfromberger** [comment]
😊

--
Dr. rer. nat. Peter Fromberger, Dipl.-Psych.

Human Medical Center Göttingen
Georg-August-University Göttingen
Clinic for Psychiatry and Psychotherapy – Forensic Psychiatry

ResearchGate. https://www.researchgate.net/profile/Peter_Fromberger
GoogleScholar. https://scholar.google.de/citations?user=5OvX8gUAAAAJ&hl=de

Adress. Rosdorfer Weg 70, 37081 Göttingen
Tel. +49 (0)551 4022108
Fax. +49 (0)551 4022110

Von: louisabauer <notifications@github.com>
Gesendet: Donnerstag, 7. November 2019 12:42
An: peterfromberger/mt-frontend-oauth <mt-frontend-oauth@noreply.github.com>
Cc: Fromberger, Peter <Peter.Fromberger@medizin.uni-goettingen.de>; State change <state_change@noreply.github.com>
Betreff: Re: [peterfromberger/mt-frontend-oauth] Client: Bei Quiz wird bei richtiger Antowrt "das ist falsch" angezeigt (#15)


Ah okay, ich wusste schon, dass es jetzt eine Feedback-Funktion gibt, mir war nur nicht klar, dass du als default für das Feedback überall "das ist falsch" einsetzt und war jetzt beim durchklicken etwas erstaunt...
