### ISSUE TITLE
Client: bei Basic Data ist der "kasten" abgeschnitten

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#16]
![grafik](https://user-images.githubusercontent.com/50659143/68389572-9a47ac80-0163-11ea-88f8-9c6dbb92da04.png)
Ich weiß nicht, ob es daran liegt, dass er keine Daten zum abrufen hat, aber das ist mir jetzt beim durchklicken auch noch aufgefallen, dass der Basic-Data-Kasten rechts abgeschnitten ist.

**Comment by peterfromberger** [comment]
Bitte erst Daten eingeben und dann prüfen, ob es immer noch so aussieht...

**Comment by louisabauer** [comment]
Es passt wenn Daten drin sind:
![grafik](https://user-images.githubusercontent.com/50659143/68390430-91f07100-0165-11ea-8af5-c41301f0a6e2.png)
