### ISSUE TITLE
Client: fehlender Zeilenumbruch bei simple assignment task

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#17]
hier wäre es schön, wenn er das dritte Item in die nächste Zeile gehen würde
![grafik](https://user-images.githubusercontent.com/50659143/68389807-1b9f3f00-0164-11ea-93fb-e5a7d34f675c.png)

**Comment by peterfromberger** [comment]
Sollte jetzt nicht mehr der Fall sein...

**Comment by louisabauer** [comment]
![grafik](https://user-images.githubusercontent.com/50659143/68860918-bced3e80-06ea-11ea-98c0-69fb23222d31.png)
Das Problem besteht immer noch... http://134.76.18.241/client/overview/3/1/4

**Comment by peterfromberger** [comment]
Das ist aber nicht ein simple assignment task! Ich schließe den Issue hier, da sich der auf simple assignments tasks bezieht; wenn das Problem noch woanders auftritt, dann bitte ein Neues Issue öffnen!
