### ISSUE TITLE
Client: "..." als Auflistung programmieren

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#18]
Kannst du "..." als Auflistung programmieren? Also, dass man das bei "bulleted List" auswählen kann
![grafik](https://user-images.githubusercontent.com/50660709/68390090-d7f90500-0164-11ea-8338-f8106e3f81d6.png)

Dann werden Stichpunkte, die über eine Zeile gehen eingerückt.
![grafik](https://user-images.githubusercontent.com/50660709/68389979-91a3a600-0164-11ea-81fc-ad8bfb3f2d6a.png)

**Comment by SonjaSchroeder** [comment]
Wir immer in der letzten Lektion genutzt
bspw. http://134.76.18.241/client/overview/1/1/8

**Comment by peterfromberger** [comment]
Das ist leider zu aufwendig; bitte nutzt die vorhandenen Listenelemente.
