### ISSUE TITLE
Client: Inhalte bei Simple Assignment Tasks nicht sichtbar

### ISSUE THREAD

**Issue by SafiyeTozdan** [peterfromberger/mt-frontend-oauth#21]
In allen Simple Assignment Tasks in Modul 6 fehlen die Inhalte. Ich habe sie nochmal neu gemacht und die alten gelöscht. Aber auch das klappt nicht.

Modul 6, Sitzung 1, Lektion 3
Modul 6, Sitzung 3, Lektion 4
Modul 6, Sitzung 4, Lektion 5

![Simple Assignment Task](https://user-images.githubusercontent.com/53052450/68681823-648c3480-0564-11ea-80df-c41ffb0d6b3b.png)

**Comment by peterfromberger** [comment]
Bei mir scheint es ohne Probleme zu funktionieren:

![grafik](https://user-images.githubusercontent.com/6342336/68753747-d1a3d680-0605-11ea-98a0-36c7fd956b4a.png)

**Comment by peterfromberger** [comment]
Magst du einfach nochmal deinen browser-Cache leeren und dann nochmals versuchen...wenn es klappt, bitte Issue schließen

**Comment by SafiyeTozdan** [comment]
ok es klappt. aber das muss noch geändert werden.

![Simple Assignment Task 2](https://user-images.githubusercontent.com/53052450/68756628-b6879580-060a-11ea-8f99-1672b8a49262.png)
