### ISSUE TITLE
Client: Simple Assignment Task Design

### ISSUE THREAD

**Issue by SafiyeTozdan** [peterfromberger/mt-frontend-oauth#23]
Die Farbzuordnung ergibt keinen Sinn.

![Simple Assignment Task 3](https://user-images.githubusercontent.com/53052450/68780356-763e0c80-0636-11ea-9fb3-15b00dcb9457.png)

**Comment by peterfromberger** [comment]
kannst du mir kurz sagen, welches Modul, Sitzung und Lektion das Beipiel ist?

**Comment by SafiyeTozdan** [comment]
Modul 6, Sitzung 4, Lektion 5
