### ISSUE TITLE
Client: Absätze

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#24]
![grafik](https://user-images.githubusercontent.com/50660709/68858069-7d235880-06e4-11ea-9014-a2dbfbaaee67.png)

Kannst du es wieder so einstellen, dass es bei einem Absatz es einen größeren Absatz zwischen den Zeilen gibt?

Früher gab es, wenn man mit der Enter-Taste einen Absatz gemacht hat eienn größeren Absatz zu nächsten Zeite und wenn man den Absatz mit der Taste in Wagtail gemacht hat keinen Abstand (also so wie jetzt)

**Comment by SonjaSchroeder** [comment]
Das Bild ist aus: 
http://134.76.18.241/client/overview/1/2/3

**Comment by peterfromberger** [comment]
sollte im nächsten update gelöst sein
