### ISSUE TITLE
Client: fehlender Zeilenumbruch bei pro contra assignment task 

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#25]
Sorry! Hier das neue Issue für den anderen aufgabentyp:
grafik
![grafik](https://user-images.githubusercontent.com/50659143/68861416-d04cd980-06eb-11ea-8f55-45e5228d10c4.png)

http://134.76.18.241/client/overview/3/1/4

**Comment by peterfromberger** [comment]
ist nach dem nächsten update bereinigr
