### ISSUE TITLE
Client: Ausrichtung des Textes in Textkästen

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#26]
![grafik](https://user-images.githubusercontent.com/50660709/68864833-0a20de80-06f2-11ea-908f-f7ac6a0376a9.png)
![grafik](https://user-images.githubusercontent.com/50660709/68864920-2fade800-06f2-11ea-87bb-dfb71cb2b03d.png)

Abstand oben und unten sollte gleich sein (jetzt ist er oben größer)

Beispiel aus http://134.76.18.241/client/overview/5/1/2

**Comment by peterfromberger** [comment]
sollte im nächsten update gelöst sein
