### ISSUE TITLE
Client: Multiple Choice Pick One Form

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#27]
![grafik](https://user-images.githubusercontent.com/50660709/68865220-bf539680-06f2-11ea-81c0-4f0c4c296926.png)

Kann der Hinweis "Sie dürfen nur eine Antwortoption auswählen" erscheinen, wenn zu viele Optionen angeklickt wurden?

Beispiel aus: Placebo http://134.76.18.241/client/overview/1/4/3

**Comment by peterfromberger** [comment]
Das ist tatsächlich relativ aufwendig und ich würde es jetzt erst einmal so lassen

**Comment by SonjaSchroeder** [comment]
Es könnte auch programmiert werden wie die Quizze - dass nur eien Antwort anklickbar ist
