### ISSUE TITLE
Client: thumbnail bei Video wird nicht angezeigt

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#29]
Ich weiß nicht, ob ich vielleicht was falsch gemacht habe, aber ich habe für das Video in http://134.76.18.241/client/overview/4/1/3 ein thumbnail (jpg) hochgeladen und das wird im Frontend nicht angezeigt.
![grafik](https://user-images.githubusercontent.com/50659143/68946237-bd510c80-07b2-11ea-830c-991ea7b48c0d.png)

**Comment by peterfromberger** [comment]
Diese funktion ist nicht integriert im Frontend. Ich lasse es mal drin, aber nicht als bug, sondern als enhancement.

**Comment by peterfromberger** [comment]
Diese Funktion wird aus zeitgründen nicht umgesetzt werden.
