### ISSUE TITLE
Client: Data Hierarchy Assignment Form Aufgabe kann nicht bearbeitet werden

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#30]
![grafik](https://user-images.githubusercontent.com/50660709/69139178-453f5b00-0ac0-11ea-804d-1a8d193827bd.png)

http://134.76.18.241/client/overview/1/1/5

**Comment by SonjaSchroeder** [comment]
Die Kästchen sind nicht anklickbar.
(in der vorherigen Version gab es zusätzlich das Problem, dass links nur Kästen an die letzte Stelle einfügen konnte)

**Comment by peterfromberger** [comment]
Ich finde keine Aufgabe unter 1/1/5

**Comment by SonjaSchroeder** [comment]
![grafik](https://user-images.githubusercontent.com/50660709/69140351-a10ae380-0ac2-11ea-9b32-ecb7bae1a96d.png)

**Comment by SonjaSchroeder** [comment]
Das ist die Data, die Default ist bei http://134.76.18.241/client/overview/1/4/6

**Comment by peterfromberger** [comment]
Aktuell geht es bei mir...gerade vorhin ging es auch nicht...kannst du mal nochmal probieren...?

![grafik](https://user-images.githubusercontent.com/6342336/69144173-ff3bc480-0aca-11ea-89a0-eac9c46a07fd.png)

**Comment by peterfromberger** [comment]
Die Reihenfolge geht nur so wie früher...da habe ich ehrlich gesagt gerade auch keine Idee...magst du dafür einen neuen Issue aufmachen? Dankeschön.

**Comment by SonjaSchroeder** [comment]
Bei mir ging es jetzt auch, ich schließe das Issue!
