### ISSUE TITLE
Client: Bei Multiple Choice Pick N Form Plus muss mehr als eien Antwort angeklickt werden

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#36]
![grafik](https://user-images.githubusercontent.com/50660709/69148358-66aa4200-0ad4-11ea-9fbd-44cb81e61a4d.png)

Bei dieser Aufgabe darf auch nur eine Sache angeklickt werden.
Noch besser: Wir können in Wagtail eine Mindestanzahl an Aussagen auswählen, die angeklickt werden müssen.

http://134.76.18.241/client/overview/1/4/3 (Placebo)

**Comment by peterfromberger** [comment]
Dann musst du Multiple Choice Pick One Form Plus nehmen. Bei den Forms habe ich es nicht so geändert wie bei den Quizzes und Tasks (da gibt es tatsächlich nur noch MC Pick N und das muss dann auch für MC Pick One verwendet werden). Bei den Forms nicht...

**Comment by SonjaSchroeder** [comment]
Bei Multiple Choice Pick One Form Plus darf allerdings nur eien Antwort angeklickt werden. Es gibt viele Fragen (bspw. welche Gründe haben Sie an @myTabu teilzunehmen) bei denen als Antwort eine Sache aber auch mehrere genannt werden dürfen. Deswegen ist Multiple Choice Pick One Form Plus kein adäquater Ersatz.
Vor der neuen @myTabu Version konnte bei Multiple Choice Pick N Form Plus (und Multiple Choice Pick N Form) auch nur eine Antwort angeklickt werden.

**Comment by peterfromberger** [comment]
In Wagtail kann noch nicht ausgewählt werden, wieviele Antworten ausgewählt werden können!

**Comment by peterfromberger** [comment]
Auf Wunsch muss man jetzt angeben, wieviele Antworten gegeben werden müssen.

**ACHTUNG: per default ist das 1 Antwort. Ihr müsst also bei allen MultipleChoicePickNForm und MultipleChoicePickNFormPlus dies entsprechend nachträglich anpassen!**

**Comment by SonjaSchroeder** [comment]
macht keinen Sinn:
Die Anzahl der Antwortoptionen, die angeklickt werden können, sollte frei sein.
(es muss nicht sein, dass wir in Wagtail die Mindesanzahl angeben können. Aber es muss möglich sein, dass der Teilnehmer nur eine Antwort anklickt; zusätzlich muss es möglich sein, dass die Teilnehmenden so viele Dinge angeben, wie sie wollen)

**Comment by peterfromberger** [comment]
Ok. Habe das rückgängig gemacht. Bitte entschuldigt das Missverständnis!
