### ISSUE TITLE
Abhängige Aufgaben funktionieren noch nicht!!!!

### ISSUE THREAD

**Issue by peterfromberger** [peterfromberger/mt-frontend-oauth#37]
Bitte nutzt noch nicht die abhängigen Aufgaben. Hier ist mir noch ein fundamentaler Fehler unterlaufen!

**Comment by peterfromberger** [comment]
Jetzt sollte alles funktionieren. Anleitung:

1. Das Ganze funktioniert innerhalb eines Moduls: In der ersten Sitzung wird zunächst eine MultipleChoicePickNForm - Aufgabe erstellt. Dabei muss unter "numberChoices" eingestellt werden, wieviele Antwortmöglichkeiten ausgewählt werden können.

2. Darauffolgenden werden so viele Sitzungen innerhalb des Moduls erstellt, wie es Antwortmöglichkeiten in der Aufgabe gibt.

3. In jeder Sitzung werden so viele Lektionen erstellt werden, wie es Antwortmöglichkeiten INSGESAMT in der Aufgabe gibt. Die Lektionen müssen als Abhängige Lektion eingestellt werden. Es muss für jede Lektion die Antwort angegeben werden, auf die sich die Lektion bezieht. 

4. In jeder Sitzung müssen lektionen für ALLE Antwortmöglichkeiten vorhanden sein.

BEISPIEL: Modul 7 (wichtig: die Übung muss natürlich gespeichert werden, sonst klappt es nicht)

**Comment by peterfromberger** [comment]
Leider muss ich noch eine neue Aufgabe spezifisch für abhängige Lektionen erstellen...

**Comment by peterfromberger** [comment]
Aufgabe nun im wagtail vorhanden: MultipleChoicePickNDependentLection

Bitte nur diese für abhängige Lektionen verwenden!  Sie Modul 7 als Beispiel...

**Comment by louisabauer** [comment]
Super! Vielen Dank :)
