### ISSUE TITLE
Client: Lektionsseiten werden falsch angezeigt

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#42]
**Describe the bug**
Lektionsseiten werden nicht an der in Wagtail zugewiesenen Stelle dargestellt:

**To Reproduce**
1. Go to 'http://134.76.18.241/client/overview/1/2/2'
2. Es ist nicht die korrekte Lektionsseite

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50660709/70052102-d93a1800-15d2-11ea-91f6-820413862c25.png)

Ich verwende FireFox

**Comment by peterfromberger** [comment]
Sollte jetzt alles in der richtigen reihenfolge sein.
