### ISSUE TITLE
Videos: Beginn eines Videos mit weiß ist optisch nicht gut.

### ISSUE THREAD

**Issue by peterfromberger** [peterfromberger/mt-frontend-oauth#44]
Vidoes beginnen scheinbar immer mit einem weißen Hintergrund. Man könnte zb auch das myTabu-Logo zu beginn zeigen, so wie es auch am Ende der Videos ist. Die Option im backend dafür funktioniert nicht; es muss also im Video selbst verändert werden.

http://localhost:8080/client/overview/1/1/5

**Comment by louisabauer** [comment]
Unsere Praktikantin Helen hat es geschafft das Logo so in den Videos einzubauen, dass das Problem m.M.n. gelöst ist :)
![grafik](https://user-images.githubusercontent.com/50659143/70988755-a576ec00-20c2-11ea-9e40-6ad52a3ae3c8.png)

**Comment by peterfromberger** [comment]
Perfekt.
