### ISSUE TITLE
Client: Notfallkoffer, "." ist komisch und kann weg

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#45]
Die Punkte hinter "Seelsorge.", "Polizei." etc. sind komisch, kannst du die bitte noch löschen?
![grafik](https://user-images.githubusercontent.com/50659143/70448722-13a72780-1aa1-11ea-8cf6-ead9b9f7731a.png)

**Comment by peterfromberger** [comment]
Ist im nächsten update geändert...
