### ISSUE TITLE
Client: Tokens können nicht in Geld umgewandelt werden

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#46]
**Describe the bug**
Wenn man versucht die Tokens in Geld umzuwandeln, verschwinden die Tokens, man bekommt aber kein Geld.

**To Reproduce**
1. Go to 'http://134.76.18.241/client/bank'
2. Tausche Tokesn in Geld um

**Screenshots**
![geld tauschen](https://user-images.githubusercontent.com/50660709/71988406-23489600-3230-11ea-802e-a33df191fdf6.PNG)

**Desktop (please complete the following information):**
firefox

**Comment by peterfromberger** [comment]
sollte mit dem neuen update funktionieren
