### ISSUE TITLE
Client: Vorhandenes Geld wird mit zu vielen Nachkommastellen angezeigt

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#47]
**Is your feature request related to a problem? Please describe.**
Im Konto werden sehr viele Stellen nach dem Komma angezeigt, wie hier:
![geld tauschen2](https://user-images.githubusercontent.com/50660709/71988629-820e0f80-3230-11ea-81d0-f6274a9ea85d.PNG)
http://134.76.18.241/client

**Describe the solution you'd like**
Es sollten nur 2 Stellen nach dem Komma angezeigt werden.

**Comment by peterfromberger** [comment]
sollte mit dem neuen update funktionieren
