### ISSUE TITLE
Client: Startseite der Intervention und des Placebos nicht gleich

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#48]
**Is your feature request related to a problem? Please describe.**
Auf der Startseite bei Placebo gibt es ein Feld mit Chats - bei der Intervention nicht
![grafik](https://user-images.githubusercontent.com/50660709/72157507-65044880-33b8-11ea-9768-469196482066.png)

**Describe the solution you'd like**
Es sollte einheitlich sein

**Comment by peterfromberger** [comment]
Das ist nun dynamisch, d.h. wenn neue Nachrichten existieren, erscheint auch die Card. Wenn nicht dann nicht. Die Klienten sollen sich ja auf das wesentliche konzentrieren. das funktioniert in der Intervention exakt genauso.
