### ISSUE TITLE
Client: Problem mit optional infos

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#50]
**Describe the bug**
Auf der Seite sind 3 optional Infos: erst eine und nach einem Text ein Block mit 2 optional Infos.
Die 2. und 3. optional Info ist nicht aufrufbar (ich habe die Inhalte gespeichert + ich habe es noch einmal probiert mit gelöschtem Cach)

**To Reproduce**
1. Go to http://134.76.18.241/client/overview/1/1/3 (Placebo)
2. Versuch die optional Infos zu öffnen

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50660709/72351997-c2163c00-36e1-11ea-911b-2cf50cae1ca1.png)

**Desktop (please complete the following information):**
 - firefox

**Comment by SonjaSchroeder** [comment]
Ich denke, dass es etwas damit zu tun hat, dass die optinal Infos am Ende der Lektionsseite sind. Ich habe ausprobiert, was passiert, wenn ich am Ende der Lektion noch eine basic info einfüge - dann kann ich beide optional Infos öffnen.

http://134.76.18.241/client/overview/1/1/5 hier (Intervention) tritt das gleiche Problem auf

**Comment by SonjaSchroeder** [comment]
![grafik](https://user-images.githubusercontent.com/50660709/74330896-d3ab3c00-4d92-11ea-9dc9-158df1f1bb33.png)

gleiches Problem gibt es auch, wenn eine zusätzliche Übung am Ende ist.

http://134.76.18.241/client/overview/5/1/6

**Comment by peterfromberger** [comment]
sollte mit dem neuen update funktionieren
