### ISSUE TITLE
Client: Intervention wird nicht mehr angezeigt (Placebo)

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#52]
**Describe the bug**
Die Interventionsseiten und der Überblick werden nicht mehr angezeigt

**To Reproduce**
1. Go to http://134.76.18.241/client/overview oder http://134.76.18.241/client/overview/1/1/2
2. Es wird nichts geladen

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50660709/72602028-e018b200-3916-11ea-901d-5603752915da.png)

**Desktop (please complete the following information):**
 - direfox

**Additional context**
Ich habe den Cach gelöscht. Das Problem besteht seit 2 Tagen.

**Comment by peterfromberger** [comment]
Das heißt, dass es vorher ging oder niemand vorher ausprobiert hat?

**Comment by SonjaSchroeder** [comment]
Es ging vorher

**Comment by peterfromberger** [comment]
Hmm,habt ihr etwas geändert seitdem, also bei der Placebointervention? Am Code habe ich nichts geändert.

**Comment by SonjaSchroeder** [comment]
Ich habe Lektionen hinzugefügt - auch welche die nicht gepublished sind. Vielleicht, hat das etwas mit dem Problem zu tun. Sonst habe ich nichts geändert.

**Comment by SonjaSchroeder** [comment]
Es geht wieder!
