### ISSUE TITLE
Client: "Speichern und Weiter" am Ende der Lektion, bringt einen nicht in die nächste Lektion

### ISSUE THREAD

**Issue by louisabauer** [peterfromberger/mt-frontend-oauth#55]
Bearbeitet und speichert man alle Inhalte einer Lektion und klickt am Ende der Lektion auf "Weiter" ploppt ja folgendes Fenster auf:
![grafik](https://user-images.githubusercontent.com/50659143/74439283-3f150c80-4e6c-11ea-83dd-a9150ebce8c2.png)
Drückt man auf "speichern und Weiter" passiert nichts. Man kommt nicht auf die nächste Lektionsseite. Versucht man nochmal "Weiter" zu klicken reagiert der Button nicht mehr.
![grafik](https://user-images.githubusercontent.com/50659143/74439298-49370b00-4e6c-11ea-9635-189d88480200.png)
Das navigieren auf die nächste Lektionsseite geht nur über die Adresszeile im Browser.

**Comment by peterfromberger** [comment]
sollte mit dem neuen update funktionieren
