### ISSUE TITLE
Client: Error 500: Internal Server Error in Placebo Bedingung

### ISSUE THREAD

**Issue by SafiyeTozdan** [peterfromberger/mt-frontend-oauth#56]
hat das major update dazu geführt, dass es in der placebo bedinung probleme gibt?
ich kann mich einloggen, aber beim nächsten klick auf irgendwas (egal was) flieg ich raus. :/

**Comment by peterfromberger** [comment]
problem gerade eben behoben; jetzt sollte auch Placebo klappen...
