### ISSUE TITLE
Client: Quizze werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#62]
**Describe the bug**
Quizze werden nicht mehr angezeigt

**To Reproduce**
Beispielsweise hier: http://134.76.18.241/client/overview/1/4/2

![grafik](https://user-images.githubusercontent.com/50660709/77407659-cd0edc00-6db6-11ea-843b-30fbb2fbd0bc.png)

* Operating System:
* Browser: FireFox

**Comment by peterfromberger** [comment]
fixed
