### ISSUE TITLE
Client: Multiple Choice Pick N Form wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#63]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/50660709/77407917-38f14480-6db7-11ea-8d2a-3f7a96de740b.png)
Man kann die Aufgabe nicht bearbeiten und kommt deswegen nicht weiter.

http://134.76.18.241/client/overview/1/4/4 (intervention)

* Browser: FireFox

**Comment by peterfromberger** [comment]
fixed with last update
