### ISSUE TITLE
Client: Textbausteine + Bilder ragen über Überschrift hinaus

### ISSUE THREAD

**Issue by SonjaSchroeder** [peterfromberger/mt-frontend-oauth#7]
![grafik](https://user-images.githubusercontent.com/50660709/68112546-e1c70200-fef1-11e9-8ee7-38a7ff280bfb.png)

**Comment by SonjaSchroeder** [comment]
![grafik](https://user-images.githubusercontent.com/50660709/68753676-bcc74300-0605-11ea-9c40-ba8517a05188.png)

Problem besteht wieder

**Comment by peterfromberger** [comment]
Kannst du mir noch die URL nennen? Also welches Modul, Sitzung, lektion?

**Comment by SonjaSchroeder** [comment]
http://134.76.18.241/client/overview/1/2/2

**Comment by SafiyeTozdan** [comment]
Bei dieser Übung ist es ähnlich (Modul 6, Sitzung 4, Lektion 7)

![Übung](https://user-images.githubusercontent.com/53052450/68781380-ff097800-0637-11ea-8f82-3086972c228a.png)

**Comment by SafiyeTozdan** [comment]
Und bei allen Rückblicken in Modul 6, Sitzung 4, Lektion 8 auch

**Comment by peterfromberger** [comment]
Sollte mit dem Update von heute gelöst sein....
